"""Add durations pilot2

Revision ID: c2fe193a1a00
Revises: ea6566e68c91
Create Date: 2025-05-25 20:38:53.556665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fe193a1a00'
down_revision = 'ea6566e68c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attentioncheck_1_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attentioncheck_1_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instructions_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('news_info_duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('news_info_duration')
        batch_op.drop_column('instructions_answer')
        batch_op.drop_column('attentioncheck_1_response')
        batch_op.drop_column('attentioncheck_1_duration')

    # ### end Alembic commands ###
