"""add instruction time

Revision ID: cda372f7b0d2
Revises: 198d6000cc3f
Create Date: 2025-06-02 17:49:48.407569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda372f7b0d2'
down_revision = '198d6000cc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction_duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('instruction_duration')

    # ### end Alembic commands ###
