"""Add full startup info

Revision ID: dfbce9e3fb50
Revises: c2fe193a1a00
Create Date: 2025-05-25 20:52:06.237852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbce9e3fb50'
down_revision = 'c2fe193a1a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startup_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('startup_info')

    # ### end Alembic commands ###
