"""Added page fields

Revision ID: fc3cad9e0b5f
Revises: 3a569ffa2737
Create Date: 2025-06-27 14:31:34.255539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3cad9e0b5f'
down_revision = '3a569ffa2737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_page_times', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('investment_page_times')

    # ### end Alembic commands ###
